# Generated by Django 2.2.5 on 2019-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('index', models.IntegerField(blank=True, null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ups', models.IntegerField(blank=True, null=True)),
                ('subreddit', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('downs', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reddit',
                'managed': False,
            },
        ),
    ]
